spring:
  application:
    name: nutrition-api
  jackson:
    deserialization:
      accept-float-as-int: false
      fail-on-unknown-properties: true
auth:
  jwt-secret: ${JWT_SECRET}
server:
  port: ${SERVER_PORT:8081}
---
spring:
  config:
    activate:
      on-profile: "!test"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: test
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
